- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache
    apt:
      update_cache: true
    tags:
    - install
    - dotfiles
  tasks:
  - include: tasks/kubectl.yaml
  - include: tasks/go.yaml
  - include: tasks/nvim.yaml
  - include: tasks/zsh.yaml
  - include: tasks/dotfiles.yaml
